version: '3.7'
services:
  cloudconfig-1:
    build:
      context: ..
      dockerfile: container/Dockerfile
      args:
        JAR_FILE: ./dist/5.0.0/cap-cloudconfig-5.0.0.jar
    ports:
     - "8001:8001"
  cloudconfig-2:
    image: container_cloudconfig-1:latest
    ports:
     - "8001"
    depends_on:
      - cloudconfig-1
  app:
    build:
      context: ..
      dockerfile: container/Dockerfile
      args:
        JAR_FILE: ./dist/5.0.0/cap-app-5.0.0.jar
    ports:
     - "8080:8080"
    links:
      - "cloudconfig-1:cloudconfig-server-1"
      - "cloudconfig-2:cloudconfig-server-2"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure