version: '3.7'
services:
  cloudconfig-1:
    build:
      context: ..
      dockerfile: container/Dockerfile
      args:
        JAR_FILE: ./dist/${TAG}/cap-cloudconfig-${TAG}.jar
    image: shawnyhw6n9/cap-cloudconfig:${TAG}-dev
    ports:
      - "8001:8001"
    environment:
      - PREFIX_CLOUDCONFIG_SERVER=cloudconfig-server
  cloudconfig-2:
    image: shawnyhw6n9/cap-cloudconfig:${TAG}-dev
    ports:
      - "8001:8001"
    depends_on:
      - cloudconfig-1
    environment:
      - PREFIX_CLOUDCONFIG_SERVER=cloudconfig-server
  app:
    build:
      context: ..
      dockerfile: container/Dockerfile
      args:
        JAR_FILE: ./dist/${TAG}/cap-app-${TAG}.jar
    image: shawnyhw6n9/cap-app:${TAG}-dev
    ports:
      - "8080:8080"
    depends_on:
      - cloudconfig-1
      - cloudconfig-2
    links:
      - "cloudconfig-1:cloudconfig-server-1"
      - "cloudconfig-2:cloudconfig-server-2"
    environment:
      - PREFIX_CLOUDCONFIG_SERVER=cloudconfig-server
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure