server:
  port: 8080

spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CAP-CLOUD-CONFIG-SERVER
  sleuth:
    sampler:
      percentage: 0.1
      #percentage: 1.0
  redis:
    jedis:
      pool:
        max-wait: 5000
        max-Idle: 50
        min-Idle: 5

# spring boot actuator
info:
  app:
    name: com.iisigroup.cap.app.CAP
    description: Cap by Spring Boot Application
    version: 5.0.0

#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh,health,info,monitor/hystrix.stream
management.endpoints.web.exposure.include: "*"

# eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8001/eureka,http://localhost:8003/eureka
      
logging:
  level:
    com:
      netflix:
        eureka: DEBUG
        discovery: DEBUG

#swaggerConfig:
  #apiVersion: 5.0.0
