server:
  port: 8080

spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CAP-CLOUD-CONFIG-SERVER

# spring boot actuator
info:
  app:
    name: com.iisigroup.cap.app.CAP
    description: Cap by Spring Boot Application
    version: 5.0.0
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info

# eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8001/eureka,http://localhost:8003/eureka
      
logging:
  level:
    com:
      netflix:
        eureka: DEBUG
        discovery: DEBUG

swaggerConfig:
  apiVersion: 5.0.0
