server:
  port: 8002

spring:
  application:
    name: spring-cloud-config-client
  cloud:
    config:
      discovery:
        enabled: true
        service-id: spring-cloud-config-server
#    bus:
#      trace:
#        enabled: true
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: admin
#    password: 123456

# spring boot actuator
info:
  app:
    name: com.iisigroup.cap.cap-cloudconfig-client
    description: Cap5 spring-cloud-config-client
    version: 5.0.0
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

