server:
  port: 8001

spring:
  application:
    name: CAP-CLOUD-CONFIG-SERVER
  cloud:
    config:
      server:
        prefix: /config-server
        git:
          uri: https://github.com/shawnyhw6n9/my-labs/
          timeout: 4
          search-paths: config-repo/cap
  boot.admin.client:
    url: http://${PREFIX_ADMIN_SERVER}-1:8088
    #url: http://localhost:8088
  zipkin:
    base-url: http://${PREFIX_TRACING}-1:9411/
    #base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 0.1
      #percentage: 1.0

management.endpoints.web.exposure.include: "*"

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${PREFIX_CLOUDCONFIG_SERVER}-1:8001/eureka,http://${PREFIX_CLOUDCONFIG_SERVER}-2:8002/eureka
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

logging.level.com.netflix:
  eureka: DEBUG
  discovery: DEBUG