server:
  port: 8001

spring:
  application:
    name: CAP-CLOUD-CONFIG-SERVER
  cloud:
    config:
      server:
        prefix: /config-server
        git:
#          uri: https://github.com/shawnyhw6n9/my-labs/
#          timeout: 4
          uri: file:///${user.home}/Documents/study/study_microservices_poc/my-labs
          search-paths: config-repo/cap

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://${PREFIX_CLOUDCONFIG_SERVER}-1:8001/eureka,http://${PREFIX_CLOUDCONFIG_SERVER}-2:8001/eureka

logging.level.com.netflix:
  eureka: DEBUG
  discovery: DEBUG