server:
  port: 8001

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shawnyhw6n9/my-labs
          search-paths: config-repo/cap

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
