server:
  port: 8001

spring:
  application:
    name: CAP-CLOUD-CONFIG-SERVER
  cloud:
    config:
      server:
        prefix: /config-server
        git:
          uri: file:///${user.home}/Documents/study/study_microservices_poc/my-labs
          search-paths: config-repo/cap
  boot.admin.client:
    url: http://localhost:8088
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0

management:
  endpoints:
    web.exposure.include: "*"
    health.sensitive: false
  endpoint.health.show-details: ALWAYS

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

logging.level.com.netflix:
  eureka: DEBUG
  discovery: DEBUG